### ISSUE TITLE
`nwg-dock-hyprland` installation on latest iso

### ISSUE THREAD

**Issue by Somnius** [AnkurAlpha/nwg-dock-hyprland-configs-by-AnkurAlpha#1]
nwg-dock doesn't exist on latest garuda hyprland iso, so in order to install it run `paru -S nwg-dock-hyprland` (choose build or bin, your choice) and then configure the `style.css`

result :
![image](https://github.com/AnkurAlpha/nwg-dock-hyprland-configs-by-AnkurAlpha/assets/144157/35bbaf65-e105-492c-bec6-d6537e3cd434)

**Comment by AnkurAlpha** [comment]
Yeah, it was never intended to be there . maybe adding `paru -S nwg-dock-hyprland` in `implement_gum.sh` script would be enough .

**Comment by Somnius** [comment]
i din't yet have the `implement_gum.sh` script cause on latest prod (oct'23) and the iso i kept and use on fresh install (dec'23) g-hyprland doesn't exist as part of the prod.

**Comment by AnkurAlpha** [comment]
So, you will need to wait basically for newer ISO to get release , currently we are working on some fixes and then we will release new ISO

An MR is there to add it with gum implementation in future : 
https://gitlab.com/garuda-linux/themes-and-settings/settings/garuda-hyprland-settings/-/merge_requests/61
