### ISSUE TITLE
After selected app in dock mouse is placed on different cords

### ISSUE THREAD

**Issue by Somnius** [AnkurAlpha/nwg-dock-hyprland-configs-by-AnkurAlpha#2]
From what i understand, when you click an app in the dock, the mouse is placed automatically in the center of the latest active app on the respective workspace.

For example if spotify is in workspace 2 and i'm in workspace 1, and i click spotify on the dock the mouse gets placed on the center of the spotify app. If that app is split in the middle with another the mouse will be placed in the center of e.g. spotify instead of the last place it was.

That may confuse the user.

I'm trying to find more information about `nwg-dock-hyprland` and the mouse placement, to remedy this. I'll report back with findings.

**Comment by Somnius** [comment]
By disabling the mouse follow (`hyprland.conf` at the `input` options as `follow_mouse = 0`) it still does the same thing.

Also asked the author about it [ :link: ](https://github.com/nwg-piotr/nwg-dock-hyprland/issues/28)

**Comment by AnkurAlpha** [comment]
I think that should be expected behavior for the mouse, and I don't see any option for it , 
you can see all the options by running `nwg-dock-hyprland --help`
I didn't find any option to disable that .

**Comment by how-to-do-frontend** [comment]
hey! i know this is old, but i was having the same very annoying experience. while scrolling the hyprland wiki, i saw a variable called no_cursor_warps and it basically fixes your problem. if this variable is true, your cursor wont jump around when you focus
